# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Modup < Formula
  desc "Interactive TUI to scan and upgrade Go modules"
  homepage "https://github.com/chaindead/modup"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chaindead/modup/releases/download/v0.2.3/modup_Darwin_x86_64.tar.gz"
      sha256 "022e6c3c2ba670f697901eb8a5a32798f7364df6a9a38dba0dd4c1bd4e7b98c5"

      def install
        bin.install "modup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chaindead/modup/releases/download/v0.2.3/modup_Darwin_arm64.tar.gz"
      sha256 "db81c76e408dd27d47de0234393a16bc201bc21a128cae109f7438704c3cd6a2"

      def install
        bin.install "modup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/chaindead/modup/releases/download/v0.2.3/modup_Linux_x86_64.tar.gz"
      sha256 "b1148107867ce0605731e00822643ba27f1f067f0e7ea60813c2a41bd8520599"
      def install
        bin.install "modup"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/chaindead/modup/releases/download/v0.2.3/modup_Linux_arm64.tar.gz"
      sha256 "a015827e266b3c0257fa24a6a1e96cd1538df7677eacbc37ca40e13bd38df6f8"
      def install
        bin.install "modup"
      end
    end
  end

  test do
    system "#{bin}/modup", "--version"
  end
end
