# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TelegramMcp < Formula
  desc "Telegram MCP server for AI assistants"
  homepage "https://github.com/chaindead/telegram-mcp"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chaindead/tooner/releases/download/v0.0.4/tooner_Darwin_x86_64.tar.gz"
      sha256 "3cb268107a7f4ed865d773f539d9795fbd76afc2dee5f9011c31208a9d40c2f3"

      define_method(:install) do
        bin.install "telegram-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chaindead/tooner/releases/download/v0.0.4/tooner_Darwin_arm64.tar.gz"
      sha256 "01946ce902a64212f4132c88adb56098af97751214f0f82a1e8d7256a9e06568"

      define_method(:install) do
        bin.install "telegram-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chaindead/tooner/releases/download/v0.0.4/tooner_Linux_x86_64.tar.gz"
      sha256 "400d35255b321534551fa8c3f78bfb386a4369cba1e2e8d6b6fc327eac092c82"
      define_method(:install) do
        bin.install "telegram-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chaindead/tooner/releases/download/v0.0.4/tooner_Linux_arm64.tar.gz"
      sha256 "9b5bbfb79a0d2d984f799af50cbc73ce2be051a1fb975186b9bd2dde7318fb87"
      define_method(:install) do
        bin.install "telegram-mcp"
      end
    end
  end

  test do
    system "#{bin}/telegram-mcp", "--version"
  end
end
