# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tooner < Formula
  desc "MCP proxy that reduces token usage via TOON format"
  homepage "https://github.com/chaindead/tooner"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chaindead/tooner/releases/download/v0.2.3/tooner_Darwin_x86_64.tar.gz"
      sha256 "b04972552ebac1fbfa77b15030fef9d0e8f2780a326a99a08e4d1d8cfd18801a"

      define_method(:install) do
        bin.install "tooner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chaindead/tooner/releases/download/v0.2.3/tooner_Darwin_arm64.tar.gz"
      sha256 "3a041583365cf61f9f93f25461a7743f36dc528e1007513bf1058446962d44bf"

      define_method(:install) do
        bin.install "tooner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chaindead/tooner/releases/download/v0.2.3/tooner_Linux_x86_64.tar.gz"
      sha256 "70563818b839c062355fa264b1a987c79bec9897df0116bbf9a321957b9c2253"
      define_method(:install) do
        bin.install "tooner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chaindead/tooner/releases/download/v0.2.3/tooner_Linux_arm64.tar.gz"
      sha256 "9a2fbbff539ea284231472f54661b4f1ff1f6647cf13f5d98a3cce2d39b5f56a"
      define_method(:install) do
        bin.install "tooner"
      end
    end
  end

  test do
    ENV["TOONER_SHOW_VERSION"] = "1"
    system "#{bin}/tooner"
  end
end
