# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tooner < Formula
  desc "MCP proxy that reduces token usage via TOON format"
  homepage "https://github.com/chaindead/tooner"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chaindead/tooner/releases/download/v0.2.2/tooner_Darwin_x86_64.tar.gz"
      sha256 "78cee9f28d65e090fcde2fc3477e6cfecf9a26bbe088313200f5c46478becd10"

      define_method(:install) do
        bin.install "tooner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chaindead/tooner/releases/download/v0.2.2/tooner_Darwin_arm64.tar.gz"
      sha256 "1060279d7a5f7dc1fc965216c27ed06e5ef16bcd5cc39969646cc9636c283a4c"

      define_method(:install) do
        bin.install "tooner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chaindead/tooner/releases/download/v0.2.2/tooner_Linux_x86_64.tar.gz"
      sha256 "63344f622136735d01be0c8c53cd709fd0fb46ae1d55cb064a54b2b2959d1a8b"
      define_method(:install) do
        bin.install "tooner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chaindead/tooner/releases/download/v0.2.2/tooner_Linux_arm64.tar.gz"
      sha256 "63a885ad2a6d20e6e94fb6310ac754cb7124589dfb25fd0e865b5a179c674090"
      define_method(:install) do
        bin.install "tooner"
      end
    end
  end

  test do
    ENV["TOONER_SHOW_VERSION"] = "1"
    system "#{bin}/tooner"
  end
end
