# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tooner < Formula
  desc "MCP proxy that reduces token usage via TOON format"
  homepage "https://github.com/chaindead/tooner"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chaindead/tooner/releases/download/v0.2.1/tooner_Darwin_x86_64.tar.gz"
      sha256 "eff979514a80bd9750c802cc9d94c938cec1615c7260832d51a23b4459aad6b5"

      define_method(:install) do
        bin.install "tooner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chaindead/tooner/releases/download/v0.2.1/tooner_Darwin_arm64.tar.gz"
      sha256 "eaece7f47ffe2697c0da5f25b5ba17c8a83023389a3d17d4048c8298a7b5658d"

      define_method(:install) do
        bin.install "tooner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chaindead/tooner/releases/download/v0.2.1/tooner_Linux_x86_64.tar.gz"
      sha256 "52014964528cdbadda92241d464014ecb4e12e5bec498b940cf193f91021865d"
      define_method(:install) do
        bin.install "tooner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chaindead/tooner/releases/download/v0.2.1/tooner_Linux_arm64.tar.gz"
      sha256 "34bb45ac3486b69309f04ce0fe1c8bac2586351ffccd8770230af3fdb440f7ea"
      define_method(:install) do
        bin.install "tooner"
      end
    end
  end

  test do
    ENV["TOONER_SHOW_VERSION"] = "1"
    system "#{bin}/tooner"
  end
end
